stages:
  - build

variables:
  DOCKER_REGISTRY: registry.gitlab.com

services:
  - docker:dind

before_script:
  - echo "Building Docker image for App"

build_app:
  stage: build
  script:
    - cd app
    - docker build -t $DOCKER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/app:$CI_COMMIT_REF_NAME .
    - docker push $DOCKER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/app:$CI_COMMIT_REF_NAME
  only:
    - branches
